version: '3.1'

services: 

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks: 
      - internal-container-network  
    volumes:
     - mariadb-data:/var/lib/mysql
     
  comservice:
    image: comservice:v2
    restart: always
    networks: 
     - internal-container-network  

  valveinventory:
    image: inventory_md:v25
    ports:
      - 8045:80
    networks: 
      - internal-container-network
    volumes:
     - sqldata:/root/.aspnet/DataProtection-Keys
    depends_on: 
       - db
   
volumes:
  sqldata:
  mariadb-data:

networks:
  internal-container-network:
    driver: bridge